services:
  nodered:
    image: nodered/node-red
    container_name: nodered
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
      - ./frontend/data:/data/shared:rw
    restart: unless-stopped
    networks:
      - appnet

  nginx:
    image: nginx:stable-alpine3.21-perl
    container_name: static-nginx
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/data:/usr/share/nginx/html/data:rw
    restart: unless-stopped
    networks:
      - appnet

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - nginx
    command: ["http", "--authtoken=${NGROK_AUTHTOKEN}", "--log=stdout", "nginx:80"]
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
